spring:
  application:
    name: chef
  datasource:
    url: jdbc:mysql://localhost:3306/vendor_db
    username: root
    password: EshaRedmath12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
